import type { Template } from "@shared/schema";

const now = () => new Date("2024-01-01T00:00:00.000Z");

export const DEFAULT_TEMPLATES: Template[] = [
  {
    id: "tmpl-shipping-alert",
    name: "택배 보류 알림",
    subject: "[CJ대한통운] 배송 주소 확인 미완료",
    body: [
      "<p>안녕하세요. CJ대한통운 고객센터입니다.</p>",
      "<p>택배 <strong>송장번호 3812-4477</strong> 건이 주소 불일치로 분류센터에서 보류되었습니다.</p>",
      "<p>48시간 내 아래 버튼을 통해 배송지와 연락처를 재확인하지 않으면 반송 처리됩니다.</p>",
      "<p>아래 \"배송지 재등록\" 버튼을 클릭하면 CJ대한통운 주소 재확인센터 페이지로 연결되며, 사내 이메일/사번/OTP를 모두 입력해야 정상 배송으로 처리된다고 안내하는 시나리오입니다.</p>",
      '<p><a href="{{TRAINING_LINK}}" target="_blank" rel="noopener noreferrer" style="display:inline-flex; align-items:center; justify-content:center; gap:8px; padding:12px 20px; border-radius:999px; background:#2563eb; color:#ffffff; text-decoration:none; font-weight:600;">배송지 재등록 바로가기</a></p>',
      "<p>버튼으로 이동하는 페이지에 개인정보를 절대 기입하지 않도록 사내에 즉시 공유해주세요.</p>",
    ].join(""),
    maliciousPageContent: [
      "<article style='font-family: Pretendard, sans-serif; line-height:1.6; max-width:560px; margin:0 auto;'>",
      "<header style='display:flex; align-items:center; gap:12px; margin-bottom:16px;'>",
      "<img src='https://static.cjlogistics.co.kr/logo.svg' alt='CJ대한통운' width='48' height='48' />",
      "<div>",
      "<p style=\"margin:0; font-size:14px; color:#0f172a;\">CJ대한통운 주소 재확인센터</p>",
      "<p style=\"margin:0; font-size:12px; color:#64748b;\">송장번호 3812-4477</p>",
      "</div>",
      "</header>",
      "<section style='background:#fff; border:1px solid #e2e8f0; border-radius:12px; padding:20px; box-shadow:rgba(15,23,42,0.08) 0 10px 20px;'>",
      "<p style='margin:0 0 12px;'>배송 재배정을 위해 <strong>담당자 개인정보와 OTP</strong>가 필요하다는 메시지로 사용자를 기만합니다.</p>",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>사내 이메일</label>",
      "<input style='width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:12px;' value='honggd@company.com' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>사번</label>",
      "<input style='width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:12px;' placeholder='예: 2024-00123' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>주민등록번호 앞 6자리</label>",
      "<input style='width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:12px;' placeholder='예: 900101' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>휴대전화 번호</label>",
      "<input style='width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:12px;' placeholder='010-0000-0000' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>OTP/보안번호</label>",
      "<input style='width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:16px;' placeholder='6자리' />",
      "<button style='width:100%; background:#2563eb; color:#fff; border:none; border-radius:8px; padding:12px; font-weight:600;'>주소 재확인 요청</button>",
      "<p style='font-size:12px; color:#94a3b8; margin-top:12px;'>※ 버튼 클릭 시 \"배송 담당자에게 전달됨\" 문구와 함께 입력값이 공격자 서버로 전송되도록 설계되어 있습니다.</p>",
      "</section>",
      "<footer style='margin-top:16px; font-size:12px; color:#94a3b8;'>본 페이지는 훈련용 악성 메일 본문 예시입니다.</footer>",
      "</article>",
    ].join(""),
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tmpl-m365-lock",
    name: "계정 잠금 해제 요청",
    subject: "[M365] 비정상 로그인 차단 - 본인 확인 필요",
    body: [
      "<p>회사 M365 시스템에서 서울 이외 지역에서의 로그인 시도가 3회 이상 감지되었습니다.</p>",
      "<p>보안을 위해 계정이 임시 잠김 처리되었으며, 1시간 내 보안센터에 접속해 본인 확인을 완료하지 않으면 업무용 메일 접근이 제한됩니다.</p>",
      "<p>아래 \"보안센터 접속\" 버튼을 클릭하면 Microsoft 365 보안센터와 동일하게 보이는 페이지로 이동해 이메일, 비밀번호, OTP, 휴대전화 번호를 모두 검증하라고 안내합니다.</p>",
      '<p><a href="{{TRAINING_LINK}}" target="_blank" rel="noopener noreferrer" style="display:inline-flex; align-items:center; justify-content:center; gap:8px; padding:12px 20px; border-radius:999px; background:#2563eb; color:#ffffff; text-decoration:none; font-weight:600;">보안센터 접속</a></p>',
      "<p>버튼으로 열리는 페이지는 공격자가 자격 증명을 수집하기 위해 제작한 악성 사이트이므로 즉시 신고해 주세요.</p>",
    ].join(""),
    maliciousPageContent: [
      "<article style='font-family: Segoe UI, sans-serif; max-width:520px; margin:0 auto; line-height:1.6;'>",
      "<header style='display:flex; align-items:center; gap:8px; margin-bottom:12px;'>",
      "<img src='https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg' alt='Microsoft 365' width='36' height='36' />",
      "<div>",
      "<p style='margin:0; font-size:13px; color:#475569;'>Microsoft 365 보안센터 (사칭)</p>",
      "<p style='margin:0; font-size:12px; color:#94a3b8;'>증빙번호 S-338120</p>",
      "</div>",
      "</header>",
      "<section style='background:#fff; border:1px solid #e2e8f0; border-radius:12px; padding:20px; box-shadow:rgba(15,23,42,0.06) 0 6px 18px;'>",
      "<p style='margin-top:0; color:#0f172a;'>비정상 로그인 차단을 위해 계정 소유 여부를 확인합니다. 아래 개인정보를 모두 입력하지 않으면 잠금이 해제되지 않는다고 안내합니다.</p>",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>사내 이메일</label>",
      "<input style='display:block; width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:12px;' value='employee@company.com' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>현재 비밀번호</label>",
      "<input type='password' style='display:block; width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:12px;' placeholder='비밀번호 입력' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>OTP/Authenticator 코드</label>",
      "<input style='display:block; width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:12px;' placeholder='6자리' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>휴대전화 번호</label>",
      "<input style='display:block; width:100%; border:1px solid #cbd5f5; border-radius:8px; padding:10px; margin-bottom:16px;' placeholder='010-0000-0000' />",
      "<button style='width:100%; background:#2563eb; color:#fff; font-weight:600; border:none; border-radius:8px; padding:12px;'>계정 잠금 해제</button>",
      "<p style='font-size:12px; color:#94a3b8; margin-top:12px;'>입력 즉시 \"본인 확인 중\" 메시지를 띄워 사용자가 대기하도록 만들고, 수집된 정보는 공격자 서버로 전송됩니다.</p>",
      "</section>",
      "</article>",
    ].join(""),
    createdAt: now(),
    updatedAt: now(),
  },
  {
    id: "tmpl-tax-refund",
    name: "연말정산 환급 서류 보완",
    subject: "[국세청] 추가 환급 대상 서류 제출 안내",
    body: [
      "<p>국세청 연말정산 시스템에서 귀하가 추가 환급 대상자로 분류되었습니다.</p>",
      "<p>환급 절차를 완료하려면 24시간 이내 소득공제 증빙 서류를 업로드해야 하며, 지연 시 환급이 취소됩니다.</p>",
      "<p>아래 버튼을 클릭하면 국세청 연말정산 센터와 동일한 UI의 페이지가 열리며, 개인정보, 계좌 정보, OTP를 모두 요구합니다.</p>",
      '<p><a href="{{TRAINING_LINK}}" target="_blank" rel="noopener noreferrer" style="display:inline-flex; align-items:center; justify-content:center; gap:8px; padding:12px 20px; border-radius:999px; background:#2563eb; color:#ffffff; text-decoration:none; font-weight:600;">환급 서류 제출</a></p>',
      "<p>실제 국세청은 이메일로 직접 서류 업로드를 요구하지 않으니, 이런 메일은 피싱 가능성이 높습니다.</p>",
    ].join(""),
    maliciousPageContent: [
      "<article style='font-family: NanumSquare, sans-serif; max-width:540px; margin:0 auto; line-height:1.7;'>",
      "<header style='display:flex; align-items:center; gap:10px; margin-bottom:14px;'>",
      "<img src='https://upload.wikimedia.org/wikipedia/commons/6/69/Emblem_of_the_National_Tax_Service_%28South_Korea%29.svg' alt='국세청' width='38' />",
      "<div>",
      "<p style='margin:0; font-size:14px; font-weight:600;'>국세청 연말정산 환급센터</p>",
      "<p style='margin:0; font-size:12px; color:#94a3b8;'>환급번호 REF-2024-1120</p>",
      "</div>",
      "</header>",
      "<section style='background:#fff; border:1px solid #e2e8f0; border-radius:12px; padding:20px; box-shadow:rgba(15,23,42,0.05) 0 8px 16px;'>",
      "<p>공제 여부 확인을 위해 개인정보와 금융 계좌 정보를 모두 입력하라고 유도합니다.</p>",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>이름</label>",
      "<input style='width:100%; border:1px solid #d0d7e3; border-radius:8px; padding:10px; margin-bottom:12px;' placeholder='홍길동' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>주민등록번호</label>",
      "<input style='width:100%; border:1px solid #d0d7e3; border-radius:8px; padding:10px; margin-bottom:12px;' placeholder='000000-0000000' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>환급 계좌번호</label>",
      "<input style='width:100%; border:1px solid #d0d7e3; border-radius:8px; padding:10px; margin-bottom:12px;' placeholder='은행 / 계좌번호' />",
      "<label style='display:block; font-size:12px; color:#475569; margin-bottom:4px;'>OTP/인증번호</label>",
      "<input style='width:100%; border:1px solid #d0d7e3; border-radius:8px; padding:10px; margin-bottom:16px;' placeholder='6자리' />",
      "<button style='width:100%; background:#1d4ed8; color:#fff; border:none; border-radius:8px; padding:12px; font-weight:600;'>환급 서류 업로드</button>",
      "<p style='font-size:12px; color:#94a3b8; margin-top:12px;'>입력 즉시 \"환급 서류 검토 중\" 메시지가 뜨며, 수집된 데이터는 공격자에게 전송됩니다.</p>",
      "</section>",
    ].join(""),
    createdAt: now(),
    updatedAt: now(),
  },
];
