export const SANITIZE_ALLOWED_TAGS = [
  "a",
  "abbr",
  "b",
  "blockquote",
  "br",
  "code",
  "del",
  "div",
  "em",
  "figure",
  "figcaption",
  "form",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hr",
  "i",
  "img",
  "input",
  "label",
  "li",
  "ol",
  "p",
  "pre",
  "section",
  "span",
  "button",
  "strong",
  "sub",
  "sup",
  "select",
  "option",
  "table",
  "textarea",
  "tbody",
  "thead",
  "tfoot",
  "tr",
  "th",
  "td",
  "u",
  "ul",
];

export const SANITIZE_ALLOWED_ATTRIBUTES: Record<string, string[]> = {
  a: ["href", "name", "target", "rel", "class", "style"],
  form: ["action", "method", "target", "class", "style"],
  img: ["src", "alt", "title", "width", "height", "style", "class"],
  input: [
    "type",
    "name",
    "value",
    "placeholder",
    "checked",
    "disabled",
    "readonly",
    "required",
    "minlength",
    "maxlength",
    "pattern",
    "min",
    "max",
    "step",
    "autocomplete",
    "class",
    "style",
    "id",
  ],
  label: ["for", "class", "style"],
  button: ["type", "name", "value", "disabled", "class", "style"],
  select: ["name", "multiple", "size", "class", "style", "id"],
  option: ["value", "selected", "disabled", "label", "class", "style"],
  textarea: [
    "name",
    "placeholder",
    "rows",
    "cols",
    "minlength",
    "maxlength",
    "disabled",
    "readonly",
    "required",
    "class",
    "style",
    "id",
  ],
  table: ["class", "style", "border", "cellpadding", "cellspacing", "width"],
  th: ["colspan", "rowspan", "class", "style"],
  td: ["colspan", "rowspan", "class", "style"],
  "*": ["class", "style", "id", "data-*"],
};
