export const SANITIZE_ALLOWED_TAGS = [
  "a",
  "abbr",
  "b",
  "blockquote",
  "br",
  "code",
  "del",
  "div",
  "em",
  "figure",
  "figcaption",
  "h1",
  "h2",
  "h3",
  "h4",
  "h5",
  "h6",
  "hr",
  "i",
  "img",
  "li",
  "ol",
  "p",
  "pre",
  "section",
  "span",
  "strong",
  "sub",
  "sup",
  "table",
  "tbody",
  "thead",
  "tfoot",
  "tr",
  "th",
  "td",
  "u",
  "ul",
];

export const SANITIZE_ALLOWED_ATTRIBUTES: Record<string, string[]> = {
  a: ["href", "name", "target", "rel", "class", "style"],
  img: ["src", "alt", "title", "width", "height", "style", "class"],
  table: ["class", "style", "border", "cellpadding", "cellspacing", "width"],
  th: ["colspan", "rowspan", "class", "style"],
  td: ["colspan", "rowspan", "class", "style"],
  "*": ["class", "style", "id", "data-*"],
};
